#!/bin/bash

# The link from Google Drive
# https://drive.google.com/open?id=1-wC0w6lZQWV6kovMxlVXJbIAlQrhXM6Y

ggID='1-wC0w6lZQWV6kovMxlVXJbIAlQrhXM6Y'
ggURL='https://drive.google.com/uc?export=download'  
filename="$(curl -sc /tmp/gcokie1 "${ggURL}&id=${ggID}" | grep -o '="uc-name.*</span>' | sed 's/.*">//;s/<.a> .*//')"
getcode="$(awk '/_warning_/ {print $NF}' /tmp/gcokie1)"  
curl -Lb /tmp/gcokie1 "${ggURL}&confirm=${getcode}&id=${ggID}" -o "${filename}"

tar xf Data.tar
rm Data.tar
