#!/bin/bash

# The link from Google Drive
# https://drive.google.com/file/d/1yX5MJAsgxEpz6LTIO3oC9fFSzPww9zME/view?usp=sharing

ggID='1yX5MJAsgxEpz6LTIO3oC9fFSzPww9zME'
ggURL='https://drive.google.com/uc?export=download'  
filename="$(curl -sc /tmp/gcokie1 "${ggURL}&id=${ggID}" | grep -o '="uc-name.*</span>' | sed 's/.*">//;s/<.a> .*//')"
getcode="$(awk '/_warning_/ {print $NF}' /tmp/gcokie1)"  
curl -Lb /tmp/gcokie1 "${ggURL}&confirm=${getcode}&id=${ggID}" -o "${filename}"

tar xf Data.tar
rm Data.tar
